version:
  name: velociraptor
  version: 0.73.3
  commit: f96ea5e
  build_time: "2024-11-04T04:42:55Z"
  ci_build_url: https://github.com/Velocidex/velociraptor/actions/runs/11658170182
  compiler: go1.23.2
  system: linux
  architecture: amd64
Client:
  server_urls:
  - https://10.0.2.20:8000/
  ca_certificate: |
    -----BEGIN CERTIFICATE-----
    MIIDSzCCAjOgAwIBAgIQGO0LR569d7Dl1dvFFLebUjANBgkqhkiG9w0BAQsFADAa
    MRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwHhcNMjYwMTI1MTkyMzM1WhcNMzYw
    MTIzMTkyMzM1WjAaMRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwggEiMA0GCSqG
    SIb3DQEBAQUAA4IBDwAwggEKAoIBAQDn64hUdh5rAXYonv9a1QcYURRtt2G8wyYn
    YDQSvvKCkxmGqX3Zfq7RRLMQkbbrMhzkEcfeY+HKbh8XwFEKec9DOrp3RShk6/Y2
    9eRkr+luSit9XjKKtpZXlCQU9sXRZkmi5MuVtER9h15zayu4hZGjwoawk8NkiMHC
    mlZ+iuazdlwKz2D8kaIjcsZqXMdSwBftr1JQRtY1Hgj6bwW1T/6XExZhhr/CEOID
    OkAlqxPi0sJsHcK5LP5LVv2NSrfigIeVX5S4vpo2eDSZzZshx2O0SAtKTy2vEmEa
    3QrZcpNqXG+HuxZMWJYXRdK5s29k7rT5yIRIVRezZLPvNyEdPY1rAgMBAAGjgYww
    gYkwDgYDVR0PAQH/BAQDAgKkMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcD
    AjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBTEYyEGlBmJ09qVUDBPzDzMPNtU
    mTAoBgNVHREEITAfgh1WZWxvY2lyYXB0b3JfY2EudmVsb2NpZGV4LmNvbTANBgkq
    hkiG9w0BAQsFAAOCAQEA1IM+Q0YM7/LmV29fTwHVmv+lyiTKL4bkaU9ETA1wQF5D
    8Wa59Xce+9d6fLWxiN00IoirR3R7C3DC/d9STL0M2baCju09DwQWBrsgcqnsXBWV
    /CbjtqaUghRfaXTYxOz/AeO+ktFde5p21sBJumF+nIImLF+cLwpWWyYxJhZLcHng
    MDiULWKh78ZdLKmjq1sY5jMDJ7JwUo/h0TsK0BV++tQJfWn/x3VvE/KM7gixayOa
    I6tUG6X4l4CePtadQ8Ojdm3K0FLsRrBKTgCkxWM5aFI8GN3CkUScaH2NQTCoVvnO
    mvXnf4o2oY7Yt8DP8IFG8tnthwi7rXCuRj6/2R3rGA==
    -----END CERTIFICATE-----
  nonce: K66sk0i/kAQ=
  writeback_darwin: /etc/velociraptor.writeback.yaml
  writeback_linux: /etc/velociraptor.writeback.yaml
  writeback_windows: $ProgramFiles\Velociraptor\velociraptor.writeback.yaml
  level2_writeback_suffix: .bak
  tempdir_windows: $ProgramFiles\Velociraptor\Tools
  max_poll: 60
  nanny_max_connection_delay: 600
  windows_installer:
    service_name: Velociraptor
    install_path: $ProgramFiles\Velociraptor\Velociraptor.exe
    service_description: Velociraptor service
  darwin_installer:
    service_name: com.velocidex.velociraptor
    install_path: /usr/local/sbin/velociraptor
  version:
    name: velociraptor
    version: 0.73.3
    commit: f96ea5e
    build_time: "2024-11-04T04:42:55Z"
    ci_build_url: https://github.com/Velocidex/velociraptor/actions/runs/11658170182
    compiler: go1.23.2
    system: linux
    architecture: amd64
  server_version:
    version: 0.73.3
    commit: f96ea5e
    build_time: "2024-11-04T04:42:55Z"
  use_self_signed_ssl: true
  max_upload_size: 5242880
  local_buffer:
    memory_size: 52428800
    disk_size: 1073741824
    filename_linux: /var/tmp/Velociraptor_Buffer.bin
    filename_windows: $TEMP/Velociraptor_Buffer.bin
    filename_darwin: /var/tmp/Velociraptor_Buffer.bin
