--- 
# Definici√≥n de variables para Controlador (10.0.2.20)

user: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          63383039383161303830316431626265323834646265663239356439643433353931316134333633
          3166663233336331333964303861626530643863336130340a363763623534613037656232313031
          64313037383031363762316336623530356664393431303932306636386462363632353930366566
          3230313334383562360a613537626434356238316161343838313334356635643230343430663238
          3662
          
becomepassword: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          62636336613936353965636430383030323731376166316636343961343838663265643462313536
          6537396162643031386132633236636561303839633466650a656664623465336462323831343632
          63323065303965346562313963653133633234633862636539323465316265646335623934316637
          3530616133306264340a666535313161306434313564306134613861636634643031633163623265
          3463
