---
# Definici√≥n de variables utilizadas para el grupo de nodos "controlador"

ansible_user: "{{user}}"
ansible_become_password: "{{becomepassword}}"
homedirectory: "/home/{{ansible_user}}"
limedirectory: "{{homedirectory}}/LiME/src"
memorydumpname: "memDump"
memorydumpextension: ".dd"
captureseconds: 30
tcpdumpname: "tcpDump"
tcpdumpextension: ".pcap"
storagepath: "{{homedirectory}}/evidenceStorage"


